
name: Reproduce
on: 
  push:
    branches:
      - main
jobs:
  Good:
    name: Release 8.4.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'
      - name: Install
        run: npm install -g npm@8.4.1
      - name: Install
        run: npm install
      - name: Do The Thing
        run: npm run release --workspaces --if-present --include-workspace-root
  Bad:
    name: Release 8.5.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'
      - name: Install
        run: npm install -g npm@8.5.0
      - name: Install
        run: npm install
      - name: Do The Thing
        run: npm run release --workspaces --if-present --include-workspace-root
  Also_Bad:
    name: Release 8.5.5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'
      - name: Install
        run: npm install -g npm@8.5.5
      - name: Install
        run: npm install
      - name: Do The Thing
        run: npm run release --workspaces --if-present --include-workspace-root
